language: go

go:
 - 1.8.x
 - 1.9.x
 - 1.10.x
 - 1.11.x

matrix:
  fast_finish: true

env:
  global:
   - GOBIN=$HOME/bin
   - PATH=$HOME/bin:$PATH

install:
 - go get -t -v ./...
 - go get -v github.com/PuerkitoBio/goquery
 - go generate -v ./...

script:
 - go tool vet -all .
 - go build ./...
 - go test -race -v ./...
